Parse
fernandobatels/fiscal-rs pull request #6
Opened 2021-07-04 22:25 UTC by fernandobatels

2021-07-23 01:48 UTC, fernandobatels commented
Depois de muita reestruturação, creio que consegui sintetizar a minha ideia para a organização dos dados. 

Alguns dados ficaram de fora, pois não quero prolongar essa PR mais ainda, mas que podem/serão tratados futuramente:
- Dados sobre o pagamento;
- Dados sobre a cobrança;
- Dados sobre o IPI, na seção de impostos dos produtos;
- Suporte a serviços/ISS

2021-07-23 11:43 UTC, otavio requested changes
Eu revisei o inicio da PR e vi umas possiveis melhorias. Da uma analisada. Todas elas parecem serem aplicaveis em mais locais.

Outro ponto eh que parece nao estar de acordo com o estilo de codigo.

2021-07-23 11:43 UTC, otavio commented on nfe/src/base/dest.rs
> +    NaoContribuinte = 9,
O valor Isento esta diferente no `enum` e no `FromStr` abaixo.

2021-07-23 11:43 UTC, otavio commented on nfe/src/base/dest.rs
> +            _ => IndicadorContribuicaoIe::Contribuinte, // 1
Eu sugiro usar uma linha para cada item do enum e o `_` usar um `unreacheable!`.

2021-07-23 11:43 UTC, otavio commented on nfe/src/base/emit.rs
> +        };
Acho que esse `if let` pode ser convertido para um `map`.

2021-07-24 12:09 UTC, fernandobatels commented on nfe/src/base/emit.rs
> +        };
Sim, parece que pode ser convertido mesmo. Como vou tentar empregar o serde, não me preocuparei com essa questão agora.

2021-07-24 12:11 UTC, fernandobatels commented
Vou tirar a PR de revisão para tentar implementar o uso do serde no lugar do parse manual.

2021-08-05 13:45 UTC, merged